### PR TITLE
Make client jar OSGi symbolic name header unique

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
Current `jakarta.websocket-api.jar` and `jakarta.websocket-client-api.jar` (2.1.0) share the same Bundle-SymbolicName and Extension-Name, which makes the jars impossible to be loaded in an OSGi environment such as Glassfish.

**Comment by markt-asf** [comment]
Thanks for catching this. I'll get this merged and re-release 2.1.0.

I think I'll also push down those two properties to the server POM. I'd rather have them set in the same place for both JARs than have to use an override for the client.

**Comment by jansupol** [comment]
@markt-asf Fyi, the 2.1.0 MANIFEST.MF also contains Bundle-Version 2.1.0.SNAPSHOT. As far as I remember, versioning in OSGi works differently than maven. I might have seen the issue that either 2.1.0.SNAPSHOT > 2.1.0, or 2.1.0-SNAPSHOT > 2.1.0.

**Comment by markt-asf** [comment]
Let me look into that.

**Comment by markt-asf** [comment]
I'm not seeing a good reason for the bundle version to be a separate property. Unless someone comes up with a good reason not to, I plan to remove the `bundle.version` property and replace all uses with `project.version`. That is probably going to be early next week now so folks have a few days to speak up if this is a bad idea.

**Comment by markt-asf** [comment]
Fixed in PR #395. Thanks for spotting this.

**Pull request merged**
